OnlineCoursePortalWeb/Controllers/CourseBookingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

using OnlineCoursePortalWeb.Models;
using OnlineCoursePortalWeb.Services;
using OnlineCoursePortalWeb.Services.IServices;
using System.Data;

namespace OnlineCoursePortalWeb.Controllers
{
    //[Area("Admin")]
    [Authorize(Roles ="Admin")]
    public class CourseBookingController : Controller
    {
        private readonly ICourseBookingService _courseBookingService;
        private readonly ICourseService _courseService;
        private readonly IApplicationUserService _applicationUserService;

        public CourseBookingController(ICourseBookingService courseBookingService,ICourseService courseService,IApplicationUserService applicationUserService)
        {
            _courseBookingService = courseBookingService;
            _courseService = courseService;
           _applicationUserService = applicationUserService;
        }
        public async Task<IActionResult> Index()
        {
            List<CourseBookingViewModel> list = new();

            var response = await _courseBookingService.GetAllAsync<APIResponse>();
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<CourseBookingViewModel>>(Convert.ToString(response.Result));
            }
            return View(list);
        }

       // [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create(int CourseId)
        {
            TempData["CourseId"] = CourseId;
            return View();
        }

       // [Authorize(Roles = "admin")]
       [HttpPost]
        
        public async Task<IActionResult> CreateCourseBooking(CourseBookingViewModel courseBookingViewModel)
        {
            courseBookingViewModel.IsApproved = "Pending";
            
            courseBookingViewModel.CourseId = Convert.ToInt32(TempData["CourseId"]);


            var response = await _courseBookingService.CreateAsync<APIResponse>(courseBookingViewModel);


            return RedirectToAction(nameof(Index));
        }



        [HttpDelete]

       // [Authorize(Roles = "admin")]
        public async Task<ActionResult> Delete(int id)
        {
            await _courseBookingService.DeleteAsync<APIResponse>(id);
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Updatebyid(int id)
        {
            await _courseBookingService.Updatebyid<APIResponse>(id);
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> UpdatebyidReject(int id)
        {
            await _courseBookingService.UpdatebyidReject<APIResponse>(id);
            return RedirectToAction("Index");
        }


        public async Task<ActionResult> Details(int id)
        {

            ViewData["Bookid"] = id;
            CourseBookingViewModel data=new CourseBookingViewModel();
            ApplicationUserViewModel data1= new ApplicationUserViewModel();
            CourseViewModel data2 = new CourseViewModel();
         var response=   _courseBookingService.Getbyid<APIResponse>(id);

            if(response != null)
            {
                data = JsonConvert.DeserializeObject<CourseBookingViewModel>(Convert.ToString(response.Result.Result));
            }
           var response2 = _applicationUserService.Getbyid<APIResponse>(data.UserEmail);

            if(response2 != null)
            {
                data1 = JsonConvert.DeserializeObject<ApplicationUserViewModel>(Convert.ToString(response2.Result.Result));
            }
          var response3 = _courseService.Getbyid<APIResponse>(data.CourseId);

            if(response3 != null)
            {
                data2 = JsonConvert.DeserializeObject<CourseViewModel>(Convert.ToString(response3.Result.Result));
            }
            DetailsOfBooking detailsOfBooking = new DetailsOfBooking()
            {
                ApplicationUserViewModel = data1,
                Course = data2
            };


            return View(detailsOfBooking);
        }
    }
}

OnlineCoursePortalWeb/Controllers/CourseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

using OnlineCoursePortalWeb.Models;
using OnlineCoursePortalWeb.Services.IServices;
using System.Data;

namespace OnlineCoursePortalWeb.Controllers
{
    //[Area("Admin")]
    [Authorize]
    public class CourseController : Controller
    {
        private readonly ICourseService _courseService;

        public CourseController(ICourseService courseService)
        {
            _courseService = courseService;
        }
        public async Task<IActionResult> Index()
        {
            List<CourseViewModel> list = new();

            var response = await _courseService.GetAllAsync<APIResponse>();
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<CourseViewModel>>(Convert.ToString(response.Result));
            }
            return View(list);
        }

       // [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create()
        {

            return View();
        }

       // [Authorize(Roles = "admin")]
        //[HttpPost]
        
        public async Task<IActionResult> CreateCourse(CourseViewModel courseViewModel)
        {

            var response = await _courseService.CreateAsync<APIResponse>(courseViewModel);


            return RedirectToAction(nameof(Index));

        }


       // [Authorize(Roles = "admin")]
        public IActionResult update(int id)
        {

            var response = _courseService.Getbyid<APIResponse>(id);
            var data = Convert.ToString(response.Result.Result);
            if (response != null)
            {
                CourseViewModel courseViewModel = JsonConvert.DeserializeObject<CourseViewModel>(data);
                return View(courseViewModel);
            }


            return View();
        }

       // [Authorize(Roles = "admin")]
        public async Task<ActionResult> Edit(CourseViewModel courseViewModel)
        {
            await _courseService.UpdateAsync<APIResponse>(courseViewModel);
            return RedirectToAction("Index");
        }

        
        
      //  [HttpDelete]
       
      // [Authorize(Roles = "admin")]
      public async Task<ActionResult> Delete(int id)
        {
            await _courseService.DeleteAsync<APIResponse>(id);
            return RedirectToAction("Index");
        }
        //public async Task<ActionResult> Details()
        //{

        //}
    }
}

OnlineCoursePortalWeb/Controllers/RoleController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace OnlineCoursePortalWeb.Controllers
{
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }
        public IActionResult Index()
        {
            var roles = _roleManager.Roles.ToList();
            return View(roles);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(IdentityRole role)
        {
            await _roleManager.CreateAsync(role);
            return RedirectToAction("Index");
        }
    }

}

OnlineCoursePortalWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineCoursePortalWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnlineCoursePortalWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OnlineCoursePortalWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Role</a>
                        </li>
                      
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Course</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="CourseBooking" asp-action="Index">CourseBooking</a>
                            </li>
                       
                    </ul>
                        
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - OnlineCoursePortalWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>